sudo: required
services: docker
language: generic
env:
  - DOCKER_FILE="Dockerfile.py2.jessie"
  - DOCKER_FILE="Dockerfile.py3.jessie"

before_install:
  - docker build -t myimage -f "$DOCKER_FILE" .

script:
  - docker run myimage
