sudo: required
services: docker
language: generic
env:
  - DOCKER_FILE="Dockerfile.debian8.py2"
  - DOCKER_FILE="Dockerfile.debian8.py3"
  - DOCKER_FILE="Dockerfile.debian9.py2"
  - DOCKER_FILE="Dockerfile.debian9.py3"
  - DOCKER_FILE="Dockerfile.fedora25.py2"
  - DOCKER_FILE="Dockerfile.fedora25.py3"
  - DOCKER_FILE="Dockerfile.ubuntu16.10.py2"
  - DOCKER_FILE="Dockerfile.ubuntu16.10.py3"

before_install:
  - docker build -t myimage -f "$DOCKER_FILE" .

script:
  - docker run myimage
