matrix:
  include:
    - os: linux
      sudo: required
      language: python
      env: DOCKER_FILE="Dockerfile.py2.jessie"
    - os: linux
      sudo: required
      env: DOCKER_FILE="Dockerfile.py3.jessie"

services:
  - docker

before_install:
  - docker build -t myimage -f "$DOCKER_FILE" .

script:
  - docker run myimage
