sudo: required
services: docker
language: generic
env:
  - DOCKER_FILE="Dockerfile.debian8.py2" PYTHON="python"
  - DOCKER_FILE="Dockerfile.debian8.py3" PYTHON="python3"
  - DOCKER_FILE="Dockerfile.debian9.py2" PYTHON="python"
  - DOCKER_FILE="Dockerfile.debian9.py3" PYTHON="python3"
  - DOCKER_FILE="Dockerfile.fedora25.py2" PYTHON="python"
  - DOCKER_FILE="Dockerfile.fedora25.py3" PYTHON="python3"
  - DOCKER_FILE="Dockerfile.ubuntu16.04.py2" PYTHON="python"
  - DOCKER_FILE="Dockerfile.ubuntu16.04.py3" PYTHON="python3"
  - DOCKER_FILE="Dockerfile.ubuntu16.10.py2" PYTHON="python"
  - DOCKER_FILE="Dockerfile.ubuntu16.10.py3" PYTHON="python3"

before_install:
  - docker build -t myimage -f "$DOCKER_FILE" .

before_script:
  - docker run --tty --detach myimage > container_id

script:
  - docker exec "$(cat container_id)" xvfb-run -a "$PYTHON" -m pytest test.py
  - docker exec "$(cat container_id)" "$PYTHON" -m pep8 --ignore=E402 test.py
  - docker exec "$(cat container_id)" "$PYTHON" -m pyflakes test.py

after_script:
  - docker stop "$(cat container_id)"
